namespace Demo.Services.Orders.API.Models
{
    public class ProductReference
    {
        // We don't use IDENTITY here because we want to preserve 
        // the exact ID generated by the Catalog service!
        public int Id { get; set; }
        public decimal Price { get; set; }
    }
}
